import { NextResponse } from "next/server";
import { createServerSupabase } from "@/lib/supabase";

// All curated deals to seed into the database
const SEED_DEALS = [
  // Myntra
  { marketplace: "Myntra", title: "Roadster Men Solid Round Neck T-Shirt", category: "Fashion", current_price: 299, original_price: 599, discount_percent: 50, product_url: "https://www.myntra.com/tshirts?rawQuery=roadster+men+solid+round+neck+t-shirt&sort=popularity", category_url: "https://www.myntra.com/men-tshirts", image_url: "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/2024/JUNE/20/zB26DJJJ_1718860890032_1.jpg", source: "curated", score: 55, is_active: true },
  { marketplace: "Myntra", title: "HRX by Hrithik Roshan Running Shoes", category: "Footwear", current_price: 1499, original_price: 2999, discount_percent: 50, product_url: "https://www.myntra.com/sports-shoes?rawQuery=hrx+by+hrithik+roshan+running+shoes&sort=popularity", category_url: "https://www.myntra.com/men-sports-shoes", image_url: "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/22168178/2023/3/9/40bd2e11-9d1f-4cb0-b4e0-40db1ca1f2e71678356662296HRXbyHrithikRoshanMenNavyBlueRunningShoes1.jpg", source: "curated", score: 35, is_active: true },
  { marketplace: "Myntra", title: "Allen Solly Men Slim Fit Formal Shirt", category: "Fashion", current_price: 899, original_price: 1699, discount_percent: 47, product_url: "https://www.myntra.com/shirts?rawQuery=allen+solly+men+slim+fit+formal+shirt&sort=popularity", category_url: "https://www.myntra.com/men-formal-shirts", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 33, is_active: true },
  { marketplace: "Myntra", title: "HIGHLANDER Men Blue Slim Fit Jeans", category: "Fashion", current_price: 599, original_price: 1499, discount_percent: 60, product_url: "https://www.myntra.com/jeans?rawQuery=highlander+men+blue+slim+fit+jeans&sort=popularity", category_url: "https://www.myntra.com/men-jeans", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 45, is_active: true },
  { marketplace: "Myntra", title: "Libas Women Printed Kurti with Trousers", category: "Fashion", current_price: 699, original_price: 1999, discount_percent: 65, product_url: "https://www.myntra.com/kurta-sets?rawQuery=libas+women+printed+kurti+trousers&sort=popularity", category_url: "https://www.myntra.com/women-kurta-sets", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 50, is_active: true },
  { marketplace: "Myntra", title: "Puma Men Resolve Modern Running Shoes", category: "Footwear", current_price: 1799, original_price: 4499, discount_percent: 60, product_url: "https://www.myntra.com/sports-shoes?rawQuery=puma+men+resolve+modern+running+shoes&sort=popularity", category_url: "https://www.myntra.com/men-sports-shoes", image_url: "https://img.icons8.com/fluency/200/running-shoe.png", source: "curated", score: 40, is_active: true },
  { marketplace: "Myntra", title: "H&M Regular Fit Cotton Shirt", category: "Fashion", current_price: 799, original_price: 1299, discount_percent: 38, product_url: "https://www.myntra.com/shirts?rawQuery=h+m+regular+fit+cotton+shirt&sort=popularity", category_url: "https://www.myntra.com/men-shirts", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 28, is_active: true },
  { marketplace: "Myntra", title: "Mast & Harbour Men White Sneakers", category: "Footwear", current_price: 799, original_price: 1999, discount_percent: 60, product_url: "https://www.myntra.com/casual-shoes?rawQuery=mast+harbour+men+white+sneakers&sort=popularity", category_url: "https://www.myntra.com/men-casual-shoes", image_url: "https://img.icons8.com/fluency/200/running-shoe.png", source: "curated", score: 45, is_active: true },

  // Meesho
  { marketplace: "Meesho", title: "Women Printed Rayon Straight Kurti", category: "Fashion", current_price: 299, original_price: 1299, discount_percent: 77, product_url: "https://www.meesho.com/search?q=women+printed+rayon+straight+kurti", category_url: "https://www.meesho.com/women-kurtis/pl/3n8", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 55, is_active: true },
  { marketplace: "Meesho", title: "Men Slim Fit Solid Casual Shirt", category: "Fashion", current_price: 349, original_price: 1499, discount_percent: 77, product_url: "https://www.meesho.com/search?q=men+slim+fit+solid+casual+shirt", category_url: "https://www.meesho.com/men-shirts/pl/3dy", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 50, is_active: true },
  { marketplace: "Meesho", title: "Women Embroidered Anarkali Kurta Set", category: "Fashion", current_price: 599, original_price: 2499, discount_percent: 76, product_url: "https://www.meesho.com/search?q=women+embroidered+anarkali+kurta+set", category_url: "https://www.meesho.com/kurta-sets/pl/3n9", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 48, is_active: true },
  { marketplace: "Meesho", title: "Unisex Casual Sneakers White", category: "Footwear", current_price: 399, original_price: 1499, discount_percent: 73, product_url: "https://www.meesho.com/search?q=unisex+casual+sneakers+white", category_url: "https://www.meesho.com/casual-shoes/pl/3w8", image_url: "https://img.icons8.com/fluency/200/running-shoe.png", source: "curated", score: 50, is_active: true },
  { marketplace: "Meesho", title: "Women Traditional Jhumka Earrings", category: "Accessories", current_price: 149, original_price: 699, discount_percent: 79, product_url: "https://www.meesho.com/search?q=women+traditional+jhumka+earrings", category_url: "https://www.meesho.com/earrings/pl/3p5", image_url: "https://img.icons8.com/fluency/200/jewelry.png", source: "curated", score: 60, is_active: true },
  { marketplace: "Meesho", title: "Stainless Steel Insulated Water Bottle", category: "Home & Kitchen", current_price: 249, original_price: 899, discount_percent: 72, product_url: "https://www.meesho.com/search?q=stainless+steel+insulated+water+bottle", category_url: "https://www.meesho.com/water-bottles/pl/41v", image_url: "https://img.icons8.com/fluency/200/kitchen.png", source: "curated", score: 55, is_active: true },
  { marketplace: "Meesho", title: "Men Cotton Regular Fit Track Pants", category: "Fashion", current_price: 299, original_price: 999, discount_percent: 70, product_url: "https://www.meesho.com/search?q=men+cotton+regular+fit+track+pants", category_url: "https://www.meesho.com/men-track-pants/pl/3dx", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 50, is_active: true },
  { marketplace: "Meesho", title: "Women Printed Chiffon Saree with Blouse", category: "Fashion", current_price: 499, original_price: 1999, discount_percent: 75, product_url: "https://www.meesho.com/search?q=women+printed+chiffon+saree", category_url: "https://www.meesho.com/sarees/pl/3nc", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 48, is_active: true },

  // Flipkart
  { marketplace: "Flipkart", title: "POCO M6 Pro 5G 128GB Smartphone", category: "Electronics", current_price: 9999, original_price: 16999, discount_percent: 41, product_url: "https://www.flipkart.com/search?q=POCO+M6+Pro+5G+128GB", category_url: "https://www.flipkart.com/mobiles/pr?sid=tyy%2C4io", image_url: "https://img.icons8.com/fluency/200/electronics.png", source: "curated", score: 30, is_active: true },
  { marketplace: "Flipkart", title: "Noise Buds VS104 Bluetooth Earbuds", category: "Electronics", current_price: 699, original_price: 2499, discount_percent: 72, product_url: "https://www.flipkart.com/search?q=Noise+Buds+VS104+Bluetooth+Earbuds", category_url: "https://www.flipkart.com/audio-video/headphones/pr?sid=0pm%2Cfcn", image_url: "https://img.icons8.com/fluency/200/electronics.png", source: "curated", score: 55, is_active: true },
  { marketplace: "Flipkart", title: "Campus NORTH Plus Running Shoes", category: "Footwear", current_price: 699, original_price: 1699, discount_percent: 59, product_url: "https://www.flipkart.com/search?q=Campus+NORTH+Plus+Running+Shoes", category_url: "https://www.flipkart.com/mens-footwear/sports-shoes/pr?sid=osp%2Ccil%2C1cu", image_url: "https://img.icons8.com/fluency/200/running-shoe.png", source: "curated", score: 45, is_active: true },
  { marketplace: "Flipkart", title: "Puma Men Solid Polo Neck T-Shirt", category: "Fashion", current_price: 599, original_price: 1999, discount_percent: 70, product_url: "https://www.flipkart.com/search?q=Puma+Men+Solid+Polo+Neck+T-Shirt", category_url: "https://www.flipkart.com/men-tshirts/pr?sid=clo%2Cash%2Cank", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 55, is_active: true },
  { marketplace: "Flipkart", title: "Samsung 32 inch HD Ready LED Smart TV", category: "Electronics", current_price: 11490, original_price: 19900, discount_percent: 42, product_url: "https://www.flipkart.com/search?q=Samsung+32+inch+HD+Ready+LED+Smart+TV", category_url: "https://www.flipkart.com/televisions/pr?sid=ckf%2Cczl", image_url: "https://img.icons8.com/fluency/200/electronics.png", source: "curated", score: 25, is_active: true },
  { marketplace: "Flipkart", title: "boAt Airdopes 141 Wireless Earbuds", category: "Electronics", current_price: 899, original_price: 4490, discount_percent: 80, product_url: "https://www.flipkart.com/search?q=boAt+Airdopes+141+Wireless+Earbuds", category_url: "https://www.flipkart.com/audio-video/headphones/pr?sid=0pm%2Cfcn", image_url: "https://img.icons8.com/fluency/200/electronics.png", source: "curated", score: 60, is_active: true },
  { marketplace: "Flipkart", title: "Realme Narzo N53 64GB 5G Phone", category: "Electronics", current_price: 7499, original_price: 10999, discount_percent: 32, product_url: "https://www.flipkart.com/search?q=Realme+Narzo+N53+64GB+5G", category_url: "https://www.flipkart.com/mobiles/pr?sid=tyy%2C4io", image_url: "https://img.icons8.com/fluency/200/electronics.png", source: "curated", score: 23, is_active: true },
  { marketplace: "Flipkart", title: "HP 15s Core i3 12th Gen Laptop", category: "Electronics", current_price: 33990, original_price: 48146, discount_percent: 29, product_url: "https://www.flipkart.com/search?q=HP+15s+Core+i3+12th+Gen+Laptop", category_url: "https://www.flipkart.com/laptops/pr?sid=6bo%2Cb5g", image_url: "https://img.icons8.com/fluency/200/electronics.png", source: "curated", score: 18, is_active: true },

  // Nykaa
  { marketplace: "Nykaa", title: "Maybelline Fit Me Matte+Poreless Foundation", category: "Beauty", current_price: 399, original_price: 550, discount_percent: 27, product_url: "https://www.nykaa.com/search/result/?q=maybelline+fit+me+matte+poreless+foundation", category_url: "https://www.nykaa.com/makeup/face/foundation/c/8399", image_url: "https://img.icons8.com/fluency/200/cosmetics.png", source: "curated", score: 38, is_active: true },
  { marketplace: "Nykaa", title: "Lakme 9to5 Primer + Matte Lipstick", category: "Beauty", current_price: 299, original_price: 500, discount_percent: 40, product_url: "https://www.nykaa.com/search/result/?q=lakme+9to5+primer+matte+lipstick", category_url: "https://www.nykaa.com/makeup/lips/lipstick/c/10", image_url: "https://img.icons8.com/fluency/200/cosmetics.png", source: "curated", score: 48, is_active: true },
  { marketplace: "Nykaa", title: "Cetaphil Gentle Skin Cleanser 250ml", category: "Beauty", current_price: 549, original_price: 799, discount_percent: 31, product_url: "https://www.nykaa.com/search/result/?q=cetaphil+gentle+skin+cleanser", category_url: "https://www.nykaa.com/skin/cleansers/face-wash/c/6", image_url: "https://img.icons8.com/fluency/200/cosmetics.png", source: "curated", score: 33, is_active: true },
  { marketplace: "Nykaa", title: "The Ordinary Niacinamide 10% Serum", category: "Beauty", current_price: 590, original_price: 690, discount_percent: 14, product_url: "https://www.nykaa.com/search/result/?q=the+ordinary+niacinamide+10+serum", category_url: "https://www.nykaa.com/skin/serums-and-essence/c/8397", image_url: "https://img.icons8.com/fluency/200/cosmetics.png", source: "curated", score: 18, is_active: true },
  { marketplace: "Nykaa", title: "Plum Green Tea Face Wash 100ml", category: "Beauty", current_price: 285, original_price: 380, discount_percent: 25, product_url: "https://www.nykaa.com/search/result/?q=plum+green+tea+face+wash", category_url: "https://www.nykaa.com/skin/cleansers/face-wash/c/6", image_url: "https://img.icons8.com/fluency/200/cosmetics.png", source: "curated", score: 38, is_active: true },
  { marketplace: "Nykaa", title: "L'Oreal Paris Hyaluronic Acid Serum", category: "Beauty", current_price: 599, original_price: 999, discount_percent: 40, product_url: "https://www.nykaa.com/search/result/?q=loreal+paris+hyaluronic+acid+serum", category_url: "https://www.nykaa.com/skin/serums-and-essence/c/8397", image_url: "https://img.icons8.com/fluency/200/cosmetics.png", source: "curated", score: 35, is_active: true },
  { marketplace: "Nykaa", title: "Swiss Beauty Bold Matte Lip Liner Set", category: "Beauty", current_price: 299, original_price: 499, discount_percent: 40, product_url: "https://www.nykaa.com/search/result/?q=swiss+beauty+bold+matte+lip+liner", category_url: "https://www.nykaa.com/makeup/lips/lip-liner/c/12", image_url: "https://img.icons8.com/fluency/200/cosmetics.png", source: "curated", score: 48, is_active: true },
  { marketplace: "Nykaa", title: "Nivea Soft Light Moisturising Cream", category: "Beauty", current_price: 225, original_price: 350, discount_percent: 36, product_url: "https://www.nykaa.com/search/result/?q=nivea+soft+light+moisturising+cream", category_url: "https://www.nykaa.com/skin/moisturizers/c/8398", image_url: "https://img.icons8.com/fluency/200/cosmetics.png", source: "curated", score: 43, is_active: true },

  // Shopsy
  { marketplace: "Shopsy", title: "Men Casual Cotton Shirt Pack of 2", category: "Fashion", current_price: 199, original_price: 999, discount_percent: 80, product_url: "https://www.shopsy.in/search?q=men+casual+cotton+shirt+pack+of+2", category_url: "https://www.shopsy.in/clothing/men-clothing/shirts/pr?sid=clo,ash,ank,edy", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 55, is_active: true },
  { marketplace: "Shopsy", title: "Women Printed Rayon A-Line Kurti", category: "Fashion", current_price: 249, original_price: 1299, discount_percent: 81, product_url: "https://www.shopsy.in/search?q=women+printed+rayon+a-line+kurti", category_url: "https://www.shopsy.in/clothing/women-clothing/kurtas-kurtis/pr?sid=clo,ash,ank,edy", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 55, is_active: true },
  { marketplace: "Shopsy", title: "Kids Cartoon Print School Bag 30L", category: "Accessories", current_price: 349, original_price: 999, discount_percent: 65, product_url: "https://www.shopsy.in/search?q=kids+cartoon+print+school+bag", category_url: "https://www.shopsy.in/bags-wallets-belts/bags/pr?sid=reh", image_url: "https://img.icons8.com/fluency/200/jewelry.png", source: "curated", score: 40, is_active: true },
  { marketplace: "Shopsy", title: "Unisex Lightweight Sports Running Shoes", category: "Footwear", current_price: 299, original_price: 1499, discount_percent: 80, product_url: "https://www.shopsy.in/search?q=unisex+lightweight+sports+running+shoes", category_url: "https://www.shopsy.in/footwear/mens-footwear/sports-shoes/pr?sid=osp,cil", image_url: "https://img.icons8.com/fluency/200/running-shoe.png", source: "curated", score: 55, is_active: true },
  { marketplace: "Shopsy", title: "Rechargeable LED Study Desk Lamp", category: "General", current_price: 199, original_price: 799, discount_percent: 75, product_url: "https://www.shopsy.in/search?q=rechargeable+led+study+desk+lamp", category_url: "https://www.shopsy.in/home-decor/lamps-lighting/pr?sid=arb", image_url: "https://img.icons8.com/fluency/200/shopping-bag.png", source: "curated", score: 55, is_active: true },
  { marketplace: "Shopsy", title: "Silicone Back Cover Phone Case", category: "Accessories", current_price: 99, original_price: 499, discount_percent: 80, product_url: "https://www.shopsy.in/search?q=silicone+back+cover+phone+case", category_url: "https://www.shopsy.in/mobiles-accessories/mobile-accessories/pr?sid=tyy,4mr", image_url: "https://img.icons8.com/fluency/200/jewelry.png", source: "curated", score: 55, is_active: true },
  { marketplace: "Shopsy", title: "Women Traditional Jhumka Earrings Set", category: "Accessories", current_price: 149, original_price: 599, discount_percent: 75, product_url: "https://www.shopsy.in/search?q=women+traditional+jhumka+earrings", category_url: "https://www.shopsy.in/jewellery/earrings/pr?sid=byc,fem", image_url: "https://img.icons8.com/fluency/200/jewelry.png", source: "curated", score: 50, is_active: true },
  { marketplace: "Shopsy", title: "Men Cotton Comfort Track Pants Combo", category: "Fashion", current_price: 249, original_price: 899, discount_percent: 72, product_url: "https://www.shopsy.in/search?q=men+cotton+comfort+track+pants+combo", category_url: "https://www.shopsy.in/clothing/men-clothing/track-pants/pr?sid=clo,ash,ank", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 50, is_active: true },

  // Ajio
  { marketplace: "Ajio", title: "U.S. Polo Assn. Men Slim Fit Shirt", category: "Fashion", current_price: 899, original_price: 2299, discount_percent: 61, product_url: "https://www.ajio.com/search/?text=us+polo+assn+men+slim+fit+shirt", category_url: "https://www.ajio.com/men-shirts/c/830201002", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 45, is_active: true },
  { marketplace: "Ajio", title: "United Colors of Benetton Polo T-Shirt", category: "Fashion", current_price: 599, original_price: 1499, discount_percent: 60, product_url: "https://www.ajio.com/search/?text=united+colors+of+benetton+polo+t-shirt", category_url: "https://www.ajio.com/men-tshirts/c/830201001", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 45, is_active: true },
  { marketplace: "Ajio", title: "Performax Lace-Up Running Shoes", category: "Footwear", current_price: 799, original_price: 2499, discount_percent: 68, product_url: "https://www.ajio.com/search/?text=performax+lace+up+running+shoes", category_url: "https://www.ajio.com/men-sports-shoes/c/830301003", image_url: "https://img.icons8.com/fluency/200/running-shoe.png", source: "curated", score: 50, is_active: true },
  { marketplace: "Ajio", title: "DNMX Slim Fit Joggers with Drawstring", category: "Fashion", current_price: 499, original_price: 1299, discount_percent: 62, product_url: "https://www.ajio.com/search/?text=dnmx+slim+fit+joggers+drawstring", category_url: "https://www.ajio.com/men-joggers/c/830201017", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 45, is_active: true },
  { marketplace: "Ajio", title: "Fig Graphic Print Crew-Neck T-Shirt", category: "Fashion", current_price: 349, original_price: 899, discount_percent: 61, product_url: "https://www.ajio.com/search/?text=fig+graphic+print+crew+neck+t-shirt", category_url: "https://www.ajio.com/men-tshirts/c/830201001", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 50, is_active: true },
  { marketplace: "Ajio", title: "Netplay Casual Slim Fit Chinos", category: "Fashion", current_price: 699, original_price: 1999, discount_percent: 65, product_url: "https://www.ajio.com/search/?text=netplay+casual+slim+fit+chinos", category_url: "https://www.ajio.com/men-trousers/c/830201004", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 45, is_active: true },
  { marketplace: "Ajio", title: "Teamspirit Hooded Zip-Front Sweatshirt", category: "Fashion", current_price: 599, original_price: 1799, discount_percent: 67, product_url: "https://www.ajio.com/search/?text=teamspirit+hooded+zip+front+sweatshirt", category_url: "https://www.ajio.com/men-sweatshirts/c/830201011", image_url: "https://img.icons8.com/fluency/200/clothes.png", source: "curated", score: 50, is_active: true },
  { marketplace: "Ajio", title: "Reebok Classic Court Low Sneakers", category: "Footwear", current_price: 1999, original_price: 5999, discount_percent: 67, product_url: "https://www.ajio.com/search/?text=reebok+classic+court+low+sneakers", category_url: "https://www.ajio.com/men-casual-shoes/c/830301001", image_url: "https://img.icons8.com/fluency/200/running-shoe.png", source: "curated", score: 40, is_active: true },
];

export async function POST() {
  try {
    const sb = createServerSupabase();

    // Clear existing curated deals
    await sb.from("deals").delete().eq("source", "curated");

    // Insert all seed deals
    const { data, error } = await sb.from("deals").insert(SEED_DEALS).select();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({
      status: "seeded",
      message: `Inserted ${data.length} deals into Supabase`,
      dealCount: data.length,
      marketplaces: [...new Set(data.map((d) => d.marketplace))],
    });
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
